### ISSUE TITLE
Not Showing up in my wallet

### ISSUE THREAD

**Issue by ro2alive** [NoozAbooz/Duinotize#3]
When I integrated this into my website and a few friends tried it. It didn't show up in my wallet! Is there a reason for this? I'll make sure to provide proof if you need it. Also, I'm trying this on a school Chromebook. So that might be the reason. Also, does it work with websites running off of static website hosters? (Eg. Vercel, Github Sites)

**Comment by NoozAbooz** [comment]
Sorry for the late response. There were many things wrong with the URLs, which should be fixed in the latest version. Note that some of the functions also got renamed, so please reread the README. The library should work on any website hoster (the demo page runs off github pages). You can also reference the source code behind the demo site for help.
